//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Grid__HackInOut_2._0_
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMDeviceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMDeviceInfo()
        {
            this.GridInfoes = new HashSet<GridInfo>();
        }
    
        public string DeviceSerialNumber { get; set; }
        public System.DateTime LastOnlineTime { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GridInfo> GridInfoes { get; set; }
    }
}
