//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Grid__HackInOut_2._0_
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridStatu
    {
        public string DeviceSerialNumber { get; set; }
        public decimal Status { get; set; }
        public int Voltage { get; set; }
        public int Frequency { get; set; }
        public System.DateTime LastPingTime { get; set; }
    }
}
